# define USERD		"/kernel/sys/userd"
# define CONNECTION	"/kernel/obj/connection"
# define LIB_USER	"/kernel/lib/user"
# define TELNET_USER	"/kernel/obj/telnet"
# define BINARY_USER	"/kernel/obj/binary"
