string *asn_add	   P((frame*, string*, string*, string*));
string *asn_sub	   P((frame*, string*, string*, string*));
int     asn_cmp    P((frame*, string*, string*));
string *asn_mult   P((frame*, string*, string*, string*));
string *asn_div	   P((frame*, string*, string*, string*));
string *asn_mod	   P((frame*, string*, string*));
string *asn_pow	   P((frame*, string*, string*, string*));
string *asn_lshift P((frame*, string*, Int, string*));
string *asn_rshift P((frame*, string*, Int));
string *asn_and    P((frame*, string*, string*));
string *asn_or     P((frame*, string*, string*));
string *asn_xor    P((frame*, string*, string*));
